package twilightforest.references;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.block.Block;
import twilightforest.TwilightForestMod;

public class TFBlockIds {
	public static final ResourceKey<Block> TWILIGHT_PORTAL = create("twilight_portal");
	public static final ResourceKey<Block> MASON_JAR = create("mason_jar");
	public static final ResourceKey<Block> FIREFLY_JAR = create("firefly_jar");
	public static final ResourceKey<Block> CICADA_JAR = create("cicada_jar");
	public static final ResourceKey<Block> FALLEN_LEAVES = create("fallen_leaves");
	public static final ResourceKey<Block> HUGE_LILY_PAD = create("huge_lily_pad");
	public static final ResourceKey<Block> HUGE_WATER_LILY = create("huge_water_lily");
	public static final ResourceKey<Block> ROPE = create("rope");
	public static final ResourceKey<Block> KEEPSAKE_CASKET = create("keepsake_casket");
	public static final ResourceKey<Block> ZOMBIE_SKULL_CANDLE = create("zombie_skull_candle");
	public static final ResourceKey<Block> ZOMBIE_WALL_SKULL_CANDLE = create("zombie_wall_skull_candle");
	public static final ResourceKey<Block> SKELETON_SKULL_CANDLE = create("skeleton_skull_candle");
	public static final ResourceKey<Block> SKELETON_WALL_SKULL_CANDLE = create("skeleton_wall_skull_candle");
	public static final ResourceKey<Block> WITHER_SKELE_SKULL_CANDLE = create("wither_skeleton_skull_candle");
	public static final ResourceKey<Block> WITHER_SKELE_WALL_SKULL_CANDLE = create("wither_skeleton_wall_skull_candle");
	public static final ResourceKey<Block> CREEPER_SKULL_CANDLE = create("creeper_skull_candle");
	public static final ResourceKey<Block> CREEPER_WALL_SKULL_CANDLE = create("creeper_wall_skull_candle");
	public static final ResourceKey<Block> PLAYER_SKULL_CANDLE = create("player_skull_candle");
	public static final ResourceKey<Block> PLAYER_WALL_SKULL_CANDLE = create("player_wall_skull_candle");
	public static final ResourceKey<Block> PIGLIN_SKULL_CANDLE = create("piglin_skull_candle");
	public static final ResourceKey<Block> PIGLIN_WALL_SKULL_CANDLE = create("piglin_wall_skull_candle");
	public static final ResourceKey<Block> WROUGHT_IRON_FENCE = create("wrought_iron_fence");
	public static final ResourceKey<Block> OMINOUS_FIRE = create("ominous_fire");
	public static final ResourceKey<Block> UNBREAKABLE_VANISHING_BLOCK = create("unbreakable_vanishing_block");
	public static final ResourceKey<Block> BUILT_BLOCK = create("built_block");
	public static final ResourceKey<Block> ANTIBUILT_BLOCK = create("antibuilt_block");
	public static final ResourceKey<Block> REACTOR_DEBRIS = create("reactor_debris");
	public static final ResourceKey<Block> FAKE_GOLD = create("fake_gold");
	public static final ResourceKey<Block> FAKE_DIAMOND = create("fake_diamond");
	public static final ResourceKey<Block> EXPERIMENT_115 = create("experiment_115");
	public static final ResourceKey<Block> BEANSTALK_GROWER = create("beanstalk_grower");
	public static final ResourceKey<Block> NAGA_TROPHY = create("naga_trophy");
	public static final ResourceKey<Block> LICH_TROPHY = create("lich_trophy");
	public static final ResourceKey<Block> HYDRA_TROPHY = create("hydra_trophy");
	public static final ResourceKey<Block> UR_GHAST_TROPHY = create("ur_ghast_trophy");
	public static final ResourceKey<Block> KNIGHT_PHANTOM_TROPHY = create("knight_phantom_trophy");
	public static final ResourceKey<Block> SNOW_QUEEN_TROPHY = create("snow_queen_trophy");
	public static final ResourceKey<Block> MINOSHROOM_TROPHY = create("minoshroom_trophy");
	public static final ResourceKey<Block> ALPHA_YETI_TROPHY = create("alpha_yeti_trophy");
	public static final ResourceKey<Block> QUEST_RAM_TROPHY = create("quest_ram_trophy");
	public static final ResourceKey<Block> NAGA_WALL_TROPHY = create("naga_wall_trophy");
	public static final ResourceKey<Block> LICH_WALL_TROPHY = create("lich_wall_trophy");
	public static final ResourceKey<Block> HYDRA_WALL_TROPHY = create("hydra_wall_trophy");
	public static final ResourceKey<Block> UR_GHAST_WALL_TROPHY = create("ur_ghast_wall_trophy");
	public static final ResourceKey<Block> KNIGHT_PHANTOM_WALL_TROPHY = create("knight_phantom_wall_trophy");
	public static final ResourceKey<Block> SNOW_QUEEN_WALL_TROPHY = create("snow_queen_wall_trophy");
	public static final ResourceKey<Block> MINOSHROOM_WALL_TROPHY = create("minoshroom_wall_trophy");
	public static final ResourceKey<Block> ALPHA_YETI_WALL_TROPHY = create("alpha_yeti_wall_trophy");
	public static final ResourceKey<Block> QUEST_RAM_WALL_TROPHY = create("quest_ram_wall_trophy");
	public static final ResourceKey<Block> TWILIGHT_OAK_SIGN = create("twilight_oak_sign");
	public static final ResourceKey<Block> TWILIGHT_OAK_WALL_SIGN = create("twilight_wall_sign");
	public static final ResourceKey<Block> TWILIGHT_OAK_HANGING_SIGN = create("twilight_oak_hanging_sign");
	public static final ResourceKey<Block> TWILIGHT_OAK_WALL_HANGING_SIGN = create("twilight_oak_wall_hanging_sign");
	public static final ResourceKey<Block> CANOPY_SIGN = create("canopy_sign");
	public static final ResourceKey<Block> CANOPY_WALL_SIGN = create("canopy_wall_sign");
	public static final ResourceKey<Block> CANOPY_HANGING_SIGN = create("canopy_hanging_sign");
	public static final ResourceKey<Block> CANOPY_WALL_HANGING_SIGN = create("canopy_wall_hanging_sign");
	public static final ResourceKey<Block> MANGROVE_SIGN = create("mangrove_sign");
	public static final ResourceKey<Block> MANGROVE_WALL_SIGN = create("mangrove_wall_sign");
	public static final ResourceKey<Block> MANGROVE_HANGING_SIGN = create("mangrove_hanging_sign");
	public static final ResourceKey<Block> MANGROVE_WALL_HANGING_SIGN = create("mangrove_wall_hanging_sign");
	public static final ResourceKey<Block> DARK_SIGN = create("dark_sign");
	public static final ResourceKey<Block> DARK_WALL_SIGN = create("dark_wall_sign");
	public static final ResourceKey<Block> DARK_HANGING_SIGN = create("dark_hanging_sign");
	public static final ResourceKey<Block> DARK_WALL_HANGING_SIGN = create("dark_wall_hanging_sign");
	public static final ResourceKey<Block> TIME_SIGN = create("time_sign");
	public static final ResourceKey<Block> TIME_WALL_SIGN = create("time_wall_sign");
	public static final ResourceKey<Block> TIME_HANGING_SIGN = create("time_hanging_sign");
	public static final ResourceKey<Block> TIME_WALL_HANGING_SIGN = create("time_wall_hanging_sign");
	public static final ResourceKey<Block> TRANSFORMATION_SIGN = create("transformation_sign");
	public static final ResourceKey<Block> TRANSFORMATION_WALL_SIGN = create("transformation_wall_sign");
	public static final ResourceKey<Block> TRANSFORMATION_HANGING_SIGN = create("transformation_hanging_sign");
	public static final ResourceKey<Block> TRANSFORMATION_WALL_HANGING_SIGN = create("transformation_wall_hanging_sign");
	public static final ResourceKey<Block> MINING_SIGN = create("mining_sign");
	public static final ResourceKey<Block> MINING_WALL_SIGN = create("mining_wall_sign");
	public static final ResourceKey<Block> MINING_HANGING_SIGN = create("mining_hanging_sign");
	public static final ResourceKey<Block> MINING_WALL_HANGING_SIGN = create("mining_wall_hanging_sign");
	public static final ResourceKey<Block> SORTING_SIGN = create("sorting_sign");
	public static final ResourceKey<Block> SORTING_WALL_SIGN = create("sorting_wall_sign");
	public static final ResourceKey<Block> SORTING_HANGING_SIGN = create("sorting_hanging_sign");
	public static final ResourceKey<Block> SORTING_WALL_HANGING_SIGN = create("sorting_wall_hanging_sign");
	public static final ResourceKey<Block> POTTED_TWILIGHT_OAK_SAPLING = create("potted_twilight_oak_sapling");
	public static final ResourceKey<Block> POTTED_CANOPY_SAPLING = create("potted_canopy_sapling");
	public static final ResourceKey<Block> POTTED_MANGROVE_SAPLING = create("potted_mangrove_sapling");
	public static final ResourceKey<Block> POTTED_DARKWOOD_SAPLING = create("potted_darkwood_sapling");
	public static final ResourceKey<Block> POTTED_HOLLOW_OAK_SAPLING = create("potted_hollow_oak_sapling");
	public static final ResourceKey<Block> POTTED_RAINBOW_OAK_SAPLING = create("potted_rainbow_oak_sapling");
	public static final ResourceKey<Block> POTTED_TIME_SAPLING = create("potted_time_sapling");
	public static final ResourceKey<Block> POTTED_TRANSFORMATION_SAPLING = create("potted_transformation_sapling");
	public static final ResourceKey<Block> POTTED_MINING_SAPLING = create("potted_mining_sapling");
	public static final ResourceKey<Block> POTTED_SORTING_SAPLING = create("potted_sorting_sapling");
	public static final ResourceKey<Block> POTTED_MAYAPPLE = create("potted_mayapple");
	public static final ResourceKey<Block> POTTED_FIDDLEHEAD = create("potted_fiddlehead");
	public static final ResourceKey<Block> POTTED_MUSHGLOOM = create("potted_mushgloom");
	public static final ResourceKey<Block> POTTED_THORN = create("potted_thorn");
	public static final ResourceKey<Block> POTTED_GREEN_THORN = create("potted_green_thorn");
	public static final ResourceKey<Block> POTTED_DEAD_THORN = create("potted_dead_thorn");

	// [VanillaCopy] from BlockIds but with our own Identifier namespace
	private static ResourceKey<Block> create(String name) {
		return ResourceKey.create(Registries.BLOCK, TwilightForestMod.prefix(name));
	}
}