package twilightforest.init;

import net.minecraft.core.Direction;
import net.minecraft.core.HolderSet;
import net.minecraft.core.component.DataComponents;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.tags.DamageTypeTags;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.entity.EquipmentSlotGroup;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.ai.attributes.AttributeModifier;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.food.FoodProperties;
import net.minecraft.world.item.*;
import net.minecraft.world.item.component.BlocksAttacks;
import net.minecraft.world.item.component.DyedItemColor;
import net.minecraft.world.item.component.ItemAttributeModifiers;
import net.minecraft.world.item.component.TooltipDisplay;
import net.minecraft.world.item.enchantment.Repairable;
import net.minecraft.world.item.equipment.ArmorType;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredRegister;
import tamaized.beanification.Autowired;
import twilightforest.TwilightForestMod;
import twilightforest.components.item.PotionFlaskComponent;
import twilightforest.enums.extensions.TFRarityEnumExtension;
import twilightforest.item.*;
import twilightforest.item.food.TFConsumables;
import twilightforest.item.food.TFFoods;
import twilightforest.item.travellers_gear.TravellersArmorBeltItem;
import twilightforest.item.travellers_gear.TravellersArmorItem;
import twilightforest.item.travellers_gear.TravellersGogglesItem;
import twilightforest.references.TFItemIds;
import twilightforest.tags.TFBannerPatternTags;

import java.util.List;
import java.util.Optional;
import java.util.function.Function;
import java.util.function.Supplier;

public class TFItems {

	@Autowired
	private static TFRarityEnumExtension tfRarityEnumExtension;

	public static final DeferredRegister.Items ITEMS = DeferredRegister.createItems(TwilightForestMod.ID);

	public static final DeferredItem<Item> NAGA_SCALE = register(TFItemIds.NAGA_SCALE, Item::new, () -> new Item.Properties().rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> NAGA_CHESTPLATE = register(TFItemIds.NAGA_CHESTPLATE, Item::new, () -> new Item.Properties().humanoidArmor(TFArmorMaterials.NAGA, ArmorType.CHESTPLATE).rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> NAGA_LEGGINGS = register(TFItemIds.NAGA_LEGGINGS, Item::new, () -> new Item.Properties().humanoidArmor(TFArmorMaterials.NAGA, ArmorType.LEGGINGS).rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> TWILIGHT_SCEPTER = register(TFItemIds.TWILIGHT_SCEPTER, TwilightWandItem::new, () -> new Item.Properties().durability(99).rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> LIFEDRAIN_SCEPTER = register(TFItemIds.LIFEDRAIN_SCEPTER, LifedrainScepterItem::new, () -> new Item.Properties().durability(99).rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> ZOMBIE_SCEPTER = register(TFItemIds.ZOMBIE_SCEPTER, ZombieWandItem::new, () -> new Item.Properties().durability(9).rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> FORTIFICATION_SCEPTER = register(TFItemIds.FORTIFICATION_SCEPTER, FortificationWandItem::new, () -> new Item.Properties().durability(9).rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> EXANIMATE_ESSENCE = register(TFItemIds.EXANIMATE_ESSENCE, ExanimateEssenceItem::new, () -> new Item.Properties().rarity(Rarity.UNCOMMON).stacksTo(16));
	public static final DeferredItem<Item> WROUGHT_IRON_BAR = register(TFItemIds.WROUGHT_IRON_BAR, Item::new, Item.Properties::new);
	//items.register(Wand of Pacification [NYI], new Item().setIconIndex(6).setTranslationKey(wandPacification).setMaxStackSize(1));
	public static final DeferredItem<Item> MAGIC_PAINTING = register(TFItemIds.MAGIC_PAINTING, MagicPaintingItem::new, Item.Properties::new);
	public static final DeferredItem<Item> ORE_METER = register(TFItemIds.ORE_METER, OreMeterItem::new, () -> new Item.Properties().stacksTo(1).rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> FILLED_MAGIC_MAP = register(TFItemIds.FILLED_MAGIC_MAP, MagicMapItem::new, Item.Properties::new);
	public static final DeferredItem<Item> FILLED_MAZE_MAP = register(TFItemIds.FILLED_MAZE_MAP, properties -> new MazeMapItem(false, properties), Item.Properties::new);
	public static final DeferredItem<Item> FILLED_ORE_MAP = register(TFItemIds.FILLED_ORE_MAP, properties -> new MazeMapItem(true, properties), Item.Properties::new);
	public static final DeferredItem<Item> RAVEN_FEATHER = register(TFItemIds.RAVEN_FEATHER, Item::new, Item.Properties::new);
	public static final DeferredItem<Item> MAGIC_MAP_FOCUS = register(TFItemIds.MAGIC_MAP_FOCUS, Item::new, Item.Properties::new);
	public static final DeferredItem<Item> MAZE_MAP_FOCUS = register(TFItemIds.MAZE_MAP_FOCUS, Item::new, Item.Properties::new);
	public static final DeferredItem<Item> MAGIC_MAP = register(TFItemIds.MAGIC_MAP, EmptyMagicMapItem::new, Item.Properties::new);
	public static final DeferredItem<Item> MAZE_MAP = register(TFItemIds.MAZE_MAP, properties -> new EmptyMazeMapItem(false, properties), Item.Properties::new);
	public static final DeferredItem<Item> ORE_MAP = register(TFItemIds.ORE_MAP, properties -> new EmptyMazeMapItem(true, properties), Item.Properties::new);
	public static final DeferredItem<Item> LIVEROOT = register(TFItemIds.LIVEROOT, Item::new, Item.Properties::new);
	public static final DeferredItem<Item> RAW_IRONWOOD = register(TFItemIds.RAW_IRONWOOD, Item::new, Item.Properties::new);
	public static final DeferredItem<Item> IRONWOOD_INGOT = register(TFItemIds.IRONWOOD_INGOT, Item::new, Item.Properties::new);
	public static final DeferredItem<Item> IRONWOOD_HELMET = register(TFItemIds.IRONWOOD_HELMET, Item::new, () -> new Item.Properties().humanoidArmor(TFArmorMaterials.IRONWOOD, ArmorType.HELMET));
	public static final DeferredItem<Item> IRONWOOD_CHESTPLATE = register(TFItemIds.IRONWOOD_CHESTPLATE, Item::new, () -> new Item.Properties().humanoidArmor(TFArmorMaterials.IRONWOOD, ArmorType.CHESTPLATE));
	public static final DeferredItem<Item> IRONWOOD_LEGGINGS = register(TFItemIds.IRONWOOD_LEGGINGS, Item::new, () -> new Item.Properties().humanoidArmor(TFArmorMaterials.IRONWOOD, ArmorType.LEGGINGS));
	public static final DeferredItem<Item> IRONWOOD_BOOTS = register(TFItemIds.IRONWOOD_BOOTS, Item::new, () -> new Item.Properties().humanoidArmor(TFArmorMaterials.IRONWOOD, ArmorType.BOOTS));
	public static final DeferredItem<Item> IRONWOOD_SWORD = register(TFItemIds.IRONWOOD_SWORD, Item::new, () -> new Item.Properties().sword(TFToolMaterials.IRONWOOD, 3.0F, -2.4F));
	public static final DeferredItem<Item> IRONWOOD_SHOVEL = register(TFItemIds.IRONWOOD_SHOVEL, properties -> new ShovelItem(TFToolMaterials.IRONWOOD, 1.5F, -3.0F, properties), Item.Properties::new);
	public static final DeferredItem<Item> IRONWOOD_PICKAXE = register(TFItemIds.IRONWOOD_PICKAXE, Item::new, () -> new Item.Properties().pickaxe(TFToolMaterials.IRONWOOD, 1.0F, -2.8F));
	public static final DeferredItem<Item> IRONWOOD_AXE = register(TFItemIds.IRONWOOD_AXE, properties -> new AxeItem(TFToolMaterials.IRONWOOD, 6.0F, -3.1F, properties), Item.Properties::new);
	public static final DeferredItem<Item> IRONWOOD_HOE = register(TFItemIds.IRONWOOD_HOE, properties -> new HoeItem(TFToolMaterials.IRONWOOD, -2, -1.0F, properties), Item.Properties::new);
	public static final DeferredItem<Item> TORCHBERRIES = register(TFItemIds.TORCHBERRIES, Item::new, () -> new Item.Properties().food(TFFoods.TORCHBERRIES, TFConsumables.TORCHBERRIES));
	public static final DeferredItem<Item> RAW_VENISON = register(TFItemIds.RAW_VENISON, Item::new, () -> new Item.Properties().food(TFFoods.RAW_VENISON));
	public static final DeferredItem<Item> COOKED_VENISON = register(TFItemIds.COOKED_VENISON, Item::new, () -> new Item.Properties().food(TFFoods.VENISON_STEAK));
	public static final DeferredItem<Item> HYDRA_CHOP = register(TFItemIds.HYDRA_CHOP, HydraChopItem::new, () -> new Item.Properties().fireResistant().food(TFFoods.HYDRA_CHOP, TFConsumables.HYDRA_CHOP).rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> TANNIN = register(TFItemIds.TANNIN, Item::new, () -> new Item.Properties().craftRemainder(Items.GLASS_BOTTLE));
	public static final DeferredItem<Item> FIERY_BLOOD = register(TFItemIds.FIERY_BLOOD, Item::new, () -> new Item.Properties().rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> FIERY_TEARS = register(TFItemIds.FIERY_TEARS, Item::new, () -> new Item.Properties().rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> FIERY_INGOT = register(TFItemIds.FIERY_INGOT, Item::new, () -> new Item.Properties().fireResistant().rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> FIERY_HELMET = register(TFItemIds.FIERY_HELMET, FieryArmorItem::new, () -> new Item.Properties().humanoidArmor(TFArmorMaterials.FIERY, ArmorType.HELMET).fireResistant().rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> FIERY_CHESTPLATE = register(TFItemIds.FIERY_CHESTPLATE, FieryArmorItem::new, () -> new Item.Properties().humanoidArmor(TFArmorMaterials.FIERY, ArmorType.CHESTPLATE).fireResistant().rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> FIERY_LEGGINGS = register(TFItemIds.FIERY_LEGGINGS, FieryArmorItem::new, () -> new Item.Properties().humanoidArmor(TFArmorMaterials.FIERY, ArmorType.LEGGINGS).fireResistant().rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> FIERY_BOOTS = register(TFItemIds.FIERY_BOOTS, FieryArmorItem::new, () -> new Item.Properties().humanoidArmor(TFArmorMaterials.FIERY, ArmorType.BOOTS).fireResistant().rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> FIERY_SWORD = register(TFItemIds.FIERY_SWORD, FierySwordItem::new, () -> new Item.Properties().sword(TFToolMaterials.FIERY, 3.0F, -2.4F).fireResistant().rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> FIERY_PICKAXE = register(TFItemIds.FIERY_PICKAXE, FieryPickItem::new, () -> new Item.Properties().pickaxe(TFToolMaterials.FIERY, 1.0F, -2.8F).fireResistant().rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> TRAVELLERS_GOGGLES = register(TFItemIds.TRAVELLERS_GOGGLES, properties -> new TravellersGogglesItem(3, properties), () -> TravellersArmorItem.gogglesProperties(new Item.Properties().humanoidArmor(TFArmorMaterials.TRAVELLERS_GEAR, ArmorType.HELMET)));
	public static final DeferredItem<Item> TRAVELLERS_VEST = register(TFItemIds.TRAVELLERS_VEST, properties -> new TravellersArmorItem(3, properties), () -> TravellersArmorItem.chestProperties(new Item.Properties().humanoidArmor(TFArmorMaterials.TRAVELLERS_GEAR, ArmorType.CHESTPLATE)));
	public static final DeferredItem<Item> TRAVELLERS_GLOVES = register(TFItemIds.TRAVELLERS_GLOVES, properties -> new TravellersArmorItem(0, properties), () -> TravellersArmorItem.glovesProperties(new Item.Properties().humanoidArmor(TFArmorMaterials.TRAVELLERS_GEAR, ArmorType.CHESTPLATE).durability(0).stacksTo(1)));
	public static final DeferredItem<Item> TRAVELLERS_WINGS = register(TFItemIds.TRAVELLERS_WINGS, properties -> new TravellersArmorBeltItem(3, properties), () -> TravellersArmorItem.wingsProperties(new Item.Properties().humanoidArmor(TFArmorMaterials.TRAVELLERS_GEAR, ArmorType.LEGGINGS)));
	public static final DeferredItem<Item> TRAVELLERS_BELT = register(TFItemIds.TRAVELLERS_BELT, properties -> new TravellersArmorBeltItem(0, properties), () -> TravellersArmorBeltItem.beltProperties(new Item.Properties().humanoidArmor(TFArmorMaterials.TRAVELLERS_GEAR, ArmorType.LEGGINGS).durability(0).stacksTo(1)));
	public static final DeferredItem<Item> TRAVELLERS_BOOTS = register(TFItemIds.TRAVELLERS_BOOTS, properties -> new TravellersArmorItem(3, properties), () -> TravellersArmorItem.bootsProperties(new Item.Properties().humanoidArmor(TFArmorMaterials.TRAVELLERS_GEAR, ArmorType.BOOTS)));
	public static final DeferredItem<Item> STEELEAF_INGOT = register(TFItemIds.STEELEAF_INGOT, Item::new, Item.Properties::new);
	public static final DeferredItem<Item> STEELEAF_HELMET = register(TFItemIds.STEELEAF_HELMET, Item::new, () -> new Item.Properties().humanoidArmor(TFArmorMaterials.STEELEAF, ArmorType.HELMET));
	public static final DeferredItem<Item> STEELEAF_CHESTPLATE = register(TFItemIds.STEELEAF_CHESTPLATE, Item::new, () -> new Item.Properties().humanoidArmor(TFArmorMaterials.STEELEAF, ArmorType.CHESTPLATE));
	public static final DeferredItem<Item> STEELEAF_LEGGINGS = register(TFItemIds.STEELEAF_LEGGINGS, Item::new, () -> new Item.Properties().humanoidArmor(TFArmorMaterials.STEELEAF, ArmorType.LEGGINGS));
	public static final DeferredItem<Item> STEELEAF_BOOTS = register(TFItemIds.STEELEAF_BOOTS, Item::new, () -> new Item.Properties().humanoidArmor(TFArmorMaterials.STEELEAF, ArmorType.BOOTS));
	public static final DeferredItem<Item> STEELEAF_SWORD = register(TFItemIds.STEELEAF_SWORD, Item::new, () -> new Item.Properties().sword(TFToolMaterials.KNIGHTMETAL, 3.0F, -2.4F));
	public static final DeferredItem<Item> STEELEAF_SHOVEL = register(TFItemIds.STEELEAF_SHOVEL, properties -> new ShovelItem(TFToolMaterials.STEELEAF, 1.5F, -3.0F, properties), Item.Properties::new);
	public static final DeferredItem<Item> STEELEAF_PICKAXE = register(TFItemIds.STEELEAF_PICKAXE, Item::new, () -> new Item.Properties().pickaxe(TFToolMaterials.STEELEAF, 1.0F, -2.8F));
	public static final DeferredItem<Item> STEELEAF_AXE = register(TFItemIds.STEELEAF_AXE, properties -> new AxeItem(TFToolMaterials.STEELEAF, 6.0F, -3.0F, properties), Item.Properties::new);
	public static final DeferredItem<Item> STEELEAF_HOE = register(TFItemIds.STEELEAF_HOE, properties -> new HoeItem(TFToolMaterials.STEELEAF, -3.0F, -0.5F, properties), Item.Properties::new);
	public static final DeferredItem<Item> GOLDEN_MINOTAUR_AXE = register(TFItemIds.GOLDEN_MINOTAUR_AXE, properties -> new MinotaurAxeItem(ToolMaterial.GOLD, 6.0F, -3.2F, properties), Item.Properties::new);
	public static final DeferredItem<Item> DIAMOND_MINOTAUR_AXE = register(TFItemIds.DIAMOND_MINOTAUR_AXE, properties -> new MinotaurAxeItem(ToolMaterial.DIAMOND, 6.0F, -3.2F, properties), () -> new Item.Properties().rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> MAZEBREAKER_PICKAXE = register(TFItemIds.MAZEBREAKER_PICKAXE, MazebreakerPickItem::new, () -> new Item.Properties().pickaxe(ToolMaterial.DIAMOND, 1.0F, -2.8F).component(DataComponents.REPAIRABLE, new Repairable(HolderSet.empty())).rarity(Rarity.RARE));
	public static final DeferredItem<Item> TRANSFORMATION_POWDER = register(TFItemIds.TRANSFORMATION_POWDER, TransformPowderItem::new, Item.Properties::new);
	public static final DeferredItem<Item> RAW_MEEF = register(TFItemIds.RAW_MEEF, Item::new, () -> new Item.Properties().food(TFFoods.RAW_MEEF));
	public static final DeferredItem<Item> COOKED_MEEF = register(TFItemIds.COOKED_MEEF, Item::new, () -> new Item.Properties().food(TFFoods.MEEF_STEAK));
	public static final DeferredItem<Item> MEEF_STROGANOFF = register(TFItemIds.MEEF_STROGANOFF, Item::new, () -> new Item.Properties().stacksTo(1).rarity(Rarity.UNCOMMON).fireResistant().food(TFFoods.MEEF_STROGANOFF).usingConvertsTo(Items.BOWL));
	public static final DeferredItem<Item> MAZE_WAFER = register(TFItemIds.MAZE_WAFER, Item::new, () -> new Item.Properties().food(new FoodProperties.Builder().nutrition(4).saturationModifier(0.6F).build()));
	public static final DeferredItem<Item> MAZE_SLIME_BALL = register(TFItemIds.MAZE_SLIME_BALL, Item::new, Item.Properties::new);
	public static final DeferredItem<Item> ORE_MAGNET = register(TFItemIds.ORE_MAGNET, OreMagnetItem::new, () -> new Item.Properties().durability(64));
	public static final DeferredItem<Item> CRUMBLE_HORN = register(TFItemIds.CRUMBLE_HORN, CrumbleHornItem::new, () -> new Item.Properties().durability(1024).rarity(Rarity.RARE));
	public static final DeferredItem<Item> PEACOCK_FEATHER_FAN = register(TFItemIds.PEACOCK_FEATHER_FAN, PeacockFanItem::new, () -> new Item.Properties().durability(1024).rarity(Rarity.RARE));
	public static final DeferredItem<Item> MOONWORM_QUEEN = register(TFItemIds.MOONWORM_QUEEN, MoonwormQueenItem::new, () -> new Item.Properties().durability(256).rarity(Rarity.RARE));
	public static final DeferredItem<Item> BRITTLE_FLASK = register(TFItemIds.BRITTLE_FLASK, PotionFlaskItem::new, () -> new Item.Properties().component(TFDataComponents.POTION_FLASK_CONTENTS, PotionFlaskComponent.EMPTY));
	public static final DeferredItem<Item> GREATER_FLASK = register(TFItemIds.GREATER_FLASK, PotionFlaskItem::new, () -> new Item.Properties().stacksTo(1).rarity(Rarity.UNCOMMON).fireResistant().component(TFDataComponents.POTION_FLASK_CONTENTS, PotionFlaskComponent.EMPTY_UNBREAKABLE));
	public static final DeferredItem<Item> CHARM_OF_LIFE_1 = register(TFItemIds.CHARM_OF_LIFE_1, Item::new, () -> new Item.Properties().rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> CHARM_OF_LIFE_2 = register(TFItemIds.CHARM_OF_LIFE_2, Item::new, () -> new Item.Properties().rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> CHARM_OF_KEEPING_1 = register(TFItemIds.CHARM_OF_KEEPING_1, Item::new, () -> new Item.Properties().rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> CHARM_OF_KEEPING_2 = register(TFItemIds.CHARM_OF_KEEPING_2, Item::new, () -> new Item.Properties().rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> CHARM_OF_KEEPING_3 = register(TFItemIds.CHARM_OF_KEEPING_3, Item::new, () -> new Item.Properties().rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> IRON_BERRY = register(TFItemIds.IRON_BERRY, Item::new, Item.Properties::new);
	public static final DeferredItem<Item> GOLD_BERRY = register(TFItemIds.GOLD_BERRY, Item::new, Item.Properties::new);
	public static final DeferredItem<Item> COPPER_BERRY = register(TFItemIds.COPPER_BERRY, Item::new, Item.Properties::new);
	public static final DeferredItem<Item> ESSENCE_BERRY = register(TFItemIds.ESSENCE_BERRY, EssenceBerryItem::new, Item.Properties::new);
	public static final DeferredItem<Item> TOWER_KEY = register(TFItemIds.TOWER_KEY, Item::new, () -> new Item.Properties().fireResistant().rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> BORER_ESSENCE = register(TFItemIds.BORER_ESSENCE, Item::new, Item.Properties::new);
	public static final DeferredItem<Item> CARMINITE = register(TFItemIds.CARMINITE, Item::new, Item.Properties::new);
	public static final DeferredItem<Item> EXPERIMENT_115 = register(TFItemIds.EXPERIMENT_115, properties -> new Experiment115Item(TFBlocks.EXPERIMENT_115.get(), properties), () -> new Item.Properties().useBlockDescriptionPrefix().food(TFFoods.EXPERIMENT_115));
	public static final DeferredItem<Item> ROPE = register(TFItemIds.ROPE, properties -> new RopeItem(TFBlocks.ROPE.get(), properties), () -> new Item.Properties().useBlockDescriptionPrefix());
	public static final DeferredItem<Item> MASON_JAR = register(TFItemIds.MASON_JAR, properties -> new JarItem.MasonJarItem(TFBlocks.MASON_JAR.get(), properties), () -> new Item.Properties().useBlockDescriptionPrefix());
	public static final DeferredItem<Item> FIREFLY_JAR = register(TFItemIds.FIREFLY_JAR, properties -> new JarItem(TFBlocks.FIREFLY_JAR.get(), properties), () -> new Item.Properties().useBlockDescriptionPrefix());
	public static final DeferredItem<Item> CICADA_JAR = register(TFItemIds.CICADA_JAR, properties -> new JarItem(TFBlocks.CICADA_JAR.get(), properties), () -> new Item.Properties().useBlockDescriptionPrefix());
	public static final DeferredItem<Item> ARMOR_SHARD = register(TFItemIds.ARMOR_SHARD, Item::new, Item.Properties::new);
	public static final DeferredItem<Item> ARMOR_SHARD_CLUSTER = register(TFItemIds.ARMOR_SHARD_CLUSTER, Item::new, Item.Properties::new);
	public static final DeferredItem<Item> KNIGHTMETAL_INGOT = register(TFItemIds.KNIGHTMETAL_INGOT, Item::new, Item.Properties::new);
	public static final DeferredItem<Item> KNIGHTMETAL_HELMET = register(TFItemIds.KNIGHTMETAL_HELMET, Item::new, () -> new Item.Properties().humanoidArmor(TFArmorMaterials.KNIGHTMETAL, ArmorType.HELMET));
	public static final DeferredItem<Item> KNIGHTMETAL_CHESTPLATE = register(TFItemIds.KNIGHTMETAL_CHESTPLATE, Item::new, () -> new Item.Properties().humanoidArmor(TFArmorMaterials.KNIGHTMETAL, ArmorType.CHESTPLATE));
	public static final DeferredItem<Item> KNIGHTMETAL_LEGGINGS = register(TFItemIds.KNIGHTMETAL_LEGGINGS, Item::new, () -> new Item.Properties().humanoidArmor(TFArmorMaterials.KNIGHTMETAL, ArmorType.LEGGINGS));
	public static final DeferredItem<Item> KNIGHTMETAL_BOOTS = register(TFItemIds.KNIGHTMETAL_BOOTS, Item::new, () -> new Item.Properties().humanoidArmor(TFArmorMaterials.KNIGHTMETAL, ArmorType.BOOTS));
	public static final DeferredItem<Item> KNIGHTMETAL_SWORD = register(TFItemIds.KNIGHTMETAL_SWORD, KnightmetalToolItem::new, () -> new Item.Properties().sword(TFToolMaterials.KNIGHTMETAL, 3.0F, -2.4F));
	public static final DeferredItem<Item> KNIGHTMETAL_PICKAXE = register(TFItemIds.KNIGHTMETAL_PICKAXE, KnightmetalToolItem::new, () -> new Item.Properties().pickaxe(TFToolMaterials.KNIGHTMETAL, 1.0F, -2.8F));
	public static final DeferredItem<Item> KNIGHTMETAL_AXE = register(TFItemIds.KNIGHTMETAL_AXE, properties -> new KnightmetalAxeItem(TFToolMaterials.KNIGHTMETAL, 6.0F, -3.2F, properties), Item.Properties::new);
	public static final DeferredItem<Item> KNIGHTMETAL_RING = register(TFItemIds.KNIGHTMETAL_RING, Item::new, Item.Properties::new);
	public static final DeferredItem<Item> KNIGHTMETAL_SHIELD = register(TFItemIds.KNIGHTMETAL_SHIELD, Item::new, () -> new Item.Properties().durability(1024).equippableUnswappable(EquipmentSlot.OFFHAND).delayedComponent(DataComponents.BLOCKS_ATTACKS, context -> new BlocksAttacks(0.25F, 1.0F, List.of(new BlocksAttacks.DamageReduction(90.0F, Optional.empty(), 0.0F, 1.0F)), new BlocksAttacks.ItemDamageFunction(3.0F, 1.0F, 1.0F), Optional.of(context.getOrThrow(DamageTypeTags.BYPASSES_SHIELD)), Optional.of(SoundEvents.SHIELD_BLOCK), Optional.of(SoundEvents.SHIELD_BREAK))).component(DataComponents.BREAK_SOUND, SoundEvents.SHIELD_BREAK));
	public static final DeferredItem<Item> BLOCK_AND_CHAIN = register(TFItemIds.BLOCK_AND_CHAIN, ChainBlockItem::new, () -> new Item.Properties().durability(99));
	public static final DeferredItem<Item> PHANTOM_HELMET = register(TFItemIds.PHANTOM_HELMET, PhantomArmorItem::new, () -> new Item.Properties().humanoidArmor(TFArmorMaterials.PHANTOM, ArmorType.HELMET).rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> PHANTOM_CHESTPLATE = register(TFItemIds.PHANTOM_CHESTPLATE, PhantomArmorItem::new, () -> new Item.Properties().humanoidArmor(TFArmorMaterials.PHANTOM, ArmorType.CHESTPLATE).rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> ICE_BOMB = register(TFItemIds.ICE_BOMB, IceBombItem::new, () -> new Item.Properties().stacksTo(16));
	public static final DeferredItem<Item> ARCTIC_FUR = register(TFItemIds.ARCTIC_FUR, Item::new, Item.Properties::new);
	public static final DeferredItem<Item> ARCTIC_HELMET = register(TFItemIds.ARCTIC_HELMET, ArcticArmorItem::new, () -> new Item.Properties().humanoidArmor(TFArmorMaterials.ARCTIC, ArmorType.HELMET).component(DataComponents.DYED_COLOR, new DyedItemColor(ArcticArmorItem.DEFAULT_COLOR)));
	public static final DeferredItem<Item> ARCTIC_CHESTPLATE = register(TFItemIds.ARCTIC_CHESTPLATE, ArcticArmorItem::new, () -> new Item.Properties().humanoidArmor(TFArmorMaterials.ARCTIC, ArmorType.CHESTPLATE).component(DataComponents.DYED_COLOR, new DyedItemColor(ArcticArmorItem.DEFAULT_COLOR)));
	public static final DeferredItem<Item> ARCTIC_LEGGINGS = register(TFItemIds.ARCTIC_LEGGINGS, ArcticArmorItem::new, () -> new Item.Properties().humanoidArmor(TFArmorMaterials.ARCTIC, ArmorType.LEGGINGS).component(DataComponents.DYED_COLOR, new DyedItemColor(ArcticArmorItem.DEFAULT_COLOR)));
	public static final DeferredItem<Item> ARCTIC_BOOTS = register(TFItemIds.ARCTIC_BOOTS, ArcticArmorItem::new, () -> new Item.Properties().humanoidArmor(TFArmorMaterials.ARCTIC, ArmorType.BOOTS).component(DataComponents.DYED_COLOR, new DyedItemColor(ArcticArmorItem.DEFAULT_COLOR)));
	public static final DeferredItem<Item> ALPHA_YETI_FUR = register(TFItemIds.ALPHA_YETI_FUR, Item::new, () -> new Item.Properties().rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> YETI_HELMET = register(TFItemIds.YETI_HELMET, YetiArmorItem::new, () -> new Item.Properties().humanoidArmor(TFArmorMaterials.YETI, ArmorType.HELMET).rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> YETI_CHESTPLATE = register(TFItemIds.YETI_CHESTPLATE, YetiArmorItem::new, () -> new Item.Properties().humanoidArmor(TFArmorMaterials.YETI, ArmorType.CHESTPLATE).rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> YETI_LEGGINGS = register(TFItemIds.YETI_LEGGINGS, YetiArmorItem::new, () -> new Item.Properties().humanoidArmor(TFArmorMaterials.YETI, ArmorType.LEGGINGS).rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> YETI_BOOTS = register(TFItemIds.YETI_BOOTS, YetiArmorItem::new, () -> new Item.Properties().humanoidArmor(TFArmorMaterials.YETI, ArmorType.BOOTS).rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> TRIPLE_BOW = register(TFItemIds.TRIPLE_BOW, TripleBowItem::new, () -> new Item.Properties().rarity(Rarity.UNCOMMON).durability(384));
	public static final DeferredItem<Item> SEEKER_BOW = register(TFItemIds.SEEKER_BOW, SeekerBowItem::new, () -> new Item.Properties().rarity(Rarity.UNCOMMON).durability(384));
	public static final DeferredItem<Item> ICE_BOW = register(TFItemIds.ICE_BOW, IceBowItem::new, () -> new Item.Properties().rarity(Rarity.UNCOMMON).durability(384));
	public static final DeferredItem<Item> ENDER_BOW = register(TFItemIds.ENDER_BOW, EnderBowItem::new, () -> new Item.Properties().rarity(Rarity.UNCOMMON).durability(384));
	public static final DeferredItem<Item> ICE_SWORD = register(TFItemIds.ICE_SWORD, IceSwordItem::new, () -> new Item.Properties().sword(TFToolMaterials.ICE, 3.0F, -2.4F));
	public static final DeferredItem<Item> GLASS_SWORD = register(TFItemIds.GLASS_SWORD, GlassSwordItem::new, () -> new Item.Properties().sword(TFToolMaterials.GLASS, 3, -2.4F).rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> MAGIC_BEANS = register(TFItemIds.MAGIC_BEANS, MagicBeansItem::new, Item.Properties::new);
	public static final DeferredItem<Item> GIANT_PICKAXE = register(TFItemIds.GIANT_PICKAXE, GiantPickItem::new, () -> GiantPickItem.createGiantPickAttributes(new Item.Properties(), TFToolMaterials.GIANT, 8, -3.5F));
	public static final DeferredItem<Item> GIANT_SWORD = register(TFItemIds.GIANT_SWORD, Item::new, () -> GiantPickItem.createGiantSwordAttributes(new Item.Properties(), TFToolMaterials.GIANT, 10, -3.5F));
	public static final DeferredItem<Item> LAMP_OF_CINDERS = register(TFItemIds.LAMP_OF_CINDERS, LampOfCindersItem::new, () -> new Item.Properties().fireResistant().durability(1024).rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> CUBE_TALISMAN = register(TFItemIds.CUBE_TALISMAN, Item::new, () -> new Item.Properties().fireResistant().rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> CUBE_OF_ANNIHILATION = register(TFItemIds.CUBE_OF_ANNIHILATION, CubeOfAnnihilationItem::new, () -> new Item.Properties().stacksTo(1).fireResistant().rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> MOON_DIAL = register(TFItemIds.MOON_DIAL, MoonDialItem::new, () -> new Item.Properties().rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> POCKET_WATCH = register(TFItemIds.POCKET_WATCH, PocketWatchItem::new, () -> new Item.Properties().stacksTo(1).rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> EMPERORS_CLOTH = register(TFItemIds.EMPERORS_CLOTH, Item::new, () -> new Item.Properties().rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> FOUR_LEAF_CLOVER = register(TFItemIds.FOUR_LEAF_CLOVER, Item::new, Item.Properties::new);
	public static final DeferredItem<Item> CROWN_SPLINTER = register(TFItemIds.CROWN_SPLINTER, Item::new, () -> new Item.Properties().rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> MYSTIC_CROWN = register(TFItemIds.MYSTIC_CROWN, Item::new, () -> new Item.Properties().rarity(Rarity.UNCOMMON).stacksTo(1).attributes(ItemAttributeModifiers.builder().add(Attributes.ARMOR, new AttributeModifier(Identifier.withDefaultNamespace("armor." + EquipmentSlot.HEAD.getName()), 2.0F, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.HEAD).build()).equippable(EquipmentSlot.HEAD));
	public static final DeferredItem<Item> STALE_BREAD = register(TFItemIds.STALE_BREAD, properties -> new CustomDamageSwordItem(TFDamageTypes.STALE_SANDWICH, properties), () -> new Item.Properties().stacksTo(1).component(DataComponents.TOOLTIP_DISPLAY, TooltipDisplay.DEFAULT.withHidden(DataComponents.ATTRIBUTE_MODIFIERS, true)).sword(ToolMaterial.WOOD, 3, -2.4F));

	public static final DeferredItem<Item> KEEPSAKE_CASKET = register(TFItemIds.KEEPSAKE_CASKET, KeepsakeCasketItem::new, () -> new Item.Properties().useBlockDescriptionPrefix().rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> HUGE_LILY_PAD = register(TFItemIds.HUGE_LILY_PAD, properties -> new HugeLilyPadItem(TFBlocks.HUGE_LILY_PAD.get(), properties), () -> new Item.Properties().useBlockDescriptionPrefix());
	public static final DeferredItem<Item> HUGE_WATER_LILY = register(TFItemIds.HUGE_WATER_LILY, properties -> new PlaceOnWaterBlockItem(TFBlocks.HUGE_WATER_LILY.get(), properties), () -> new Item.Properties().useBlockDescriptionPrefix());
	public static final DeferredItem<Item> FALLEN_LEAVES = register(TFItemIds.FALLEN_LEAVES, properties -> new PlaceOnWaterBlockItem(TFBlocks.FALLEN_LEAVES.get(), properties), () -> new Item.Properties().useBlockDescriptionPrefix());
	public static final DeferredItem<Item> WROUGHT_IRON_FENCE = register(TFItemIds.WROUGHT_IRON_FENCE, properties -> new WroughtIronFenceItem(TFBlocks.WROUGHT_IRON_FENCE.get(), properties), () -> new Item.Properties().useBlockDescriptionPrefix());

	public static final DeferredItem<Item> ZOMBIE_SKULL_CANDLE = register(TFItemIds.ZOMBIE_SKULL_CANDLE, properties -> new SkullCandleItem(TFBlocks.ZOMBIE_SKULL_CANDLE.get(), TFBlocks.ZOMBIE_WALL_SKULL_CANDLE.get(), properties), () -> new Item.Properties().useBlockDescriptionPrefix().rarity(Rarity.UNCOMMON).equippable(EquipmentSlot.HEAD));
	public static final DeferredItem<Item> SKELETON_SKULL_CANDLE = register(TFItemIds.SKELETON_SKULL_CANDLE, properties -> new SkullCandleItem(TFBlocks.SKELETON_SKULL_CANDLE.get(), TFBlocks.SKELETON_WALL_SKULL_CANDLE.get(), properties), () -> new Item.Properties().useBlockDescriptionPrefix().rarity(Rarity.UNCOMMON).equippable(EquipmentSlot.HEAD));
	public static final DeferredItem<Item> WITHER_SKELETON_SKULL_CANDLE = register(TFItemIds.WITHER_SKELETON_SKULL_CANDLE, properties -> new SkullCandleItem(TFBlocks.WITHER_SKELE_SKULL_CANDLE.get(), TFBlocks.WITHER_SKELE_WALL_SKULL_CANDLE.get(), properties), () -> new Item.Properties().useBlockDescriptionPrefix().rarity(Rarity.UNCOMMON).equippable(EquipmentSlot.HEAD));
	public static final DeferredItem<Item> CREEPER_SKULL_CANDLE = register(TFItemIds.CREEPER_SKULL_CANDLE, properties -> new SkullCandleItem(TFBlocks.CREEPER_SKULL_CANDLE.get(), TFBlocks.CREEPER_WALL_SKULL_CANDLE.get(), properties), () -> new Item.Properties().useBlockDescriptionPrefix().rarity(Rarity.UNCOMMON).equippable(EquipmentSlot.HEAD));
	public static final DeferredItem<Item> PLAYER_SKULL_CANDLE = register(TFItemIds.PLAYER_SKULL_CANDLE, properties -> new SkullCandleItem(TFBlocks.PLAYER_SKULL_CANDLE.get(), TFBlocks.PLAYER_WALL_SKULL_CANDLE.get(), properties), () -> new Item.Properties().useBlockDescriptionPrefix().rarity(Rarity.UNCOMMON).equippable(EquipmentSlot.HEAD));
	public static final DeferredItem<Item> PIGLIN_SKULL_CANDLE = register(TFItemIds.PIGLIN_SKULL_CANDLE, properties -> new SkullCandleItem(TFBlocks.PIGLIN_SKULL_CANDLE.get(), TFBlocks.PIGLIN_WALL_SKULL_CANDLE.get(), properties), () -> new Item.Properties().useBlockDescriptionPrefix().rarity(Rarity.UNCOMMON).equippable(EquipmentSlot.HEAD));

	public static final DeferredItem<Item> NAGA_TROPHY = register(TFItemIds.NAGA_TROPHY, properties -> new StandingAndWallBlockItem(TFBlocks.NAGA_TROPHY.get(), TFBlocks.NAGA_WALL_TROPHY.get(), Direction.DOWN, properties), () -> new Item.Properties().useBlockDescriptionPrefix().rarity(tfRarityEnumExtension.TWILIGHT).equippable(EquipmentSlot.HEAD));
	public static final DeferredItem<Item> LICH_TROPHY = register(TFItemIds.LICH_TROPHY, properties -> new StandingAndWallBlockItem(TFBlocks.LICH_TROPHY.get(), TFBlocks.LICH_WALL_TROPHY.get(), Direction.DOWN, properties), () -> new Item.Properties().useBlockDescriptionPrefix().rarity(tfRarityEnumExtension.TWILIGHT).equippable(EquipmentSlot.HEAD));
	public static final DeferredItem<Item> MINOSHROOM_TROPHY = register(TFItemIds.MINOSHROOM_TROPHY, properties -> new StandingAndWallBlockItem(TFBlocks.MINOSHROOM_TROPHY.get(), TFBlocks.MINOSHROOM_WALL_TROPHY.get(), Direction.DOWN, properties), () -> new Item.Properties().useBlockDescriptionPrefix().rarity(tfRarityEnumExtension.TWILIGHT).equippable(EquipmentSlot.HEAD));
	public static final DeferredItem<Item> HYDRA_TROPHY = register(TFItemIds.HYDRA_TROPHY, properties -> new StandingAndWallBlockItem(TFBlocks.HYDRA_TROPHY.get(), TFBlocks.HYDRA_WALL_TROPHY.get(), Direction.DOWN, properties), () -> new Item.Properties().useBlockDescriptionPrefix().rarity(tfRarityEnumExtension.TWILIGHT).equippable(EquipmentSlot.HEAD));
	public static final DeferredItem<Item> KNIGHT_PHANTOM_TROPHY = register(TFItemIds.KNIGHT_PHANTOM_TROPHY, properties -> new StandingAndWallBlockItem(TFBlocks.KNIGHT_PHANTOM_TROPHY.get(), TFBlocks.KNIGHT_PHANTOM_WALL_TROPHY.get(), Direction.DOWN, properties), () -> new Item.Properties().useBlockDescriptionPrefix().rarity(tfRarityEnumExtension.TWILIGHT).equippable(EquipmentSlot.HEAD));
	public static final DeferredItem<Item> UR_GHAST_TROPHY = register(TFItemIds.UR_GHAST_TROPHY, properties -> new StandingAndWallBlockItem(TFBlocks.UR_GHAST_TROPHY.get(), TFBlocks.UR_GHAST_WALL_TROPHY.get(), Direction.DOWN, properties), () -> new Item.Properties().useBlockDescriptionPrefix().rarity(tfRarityEnumExtension.TWILIGHT).equippable(EquipmentSlot.HEAD));
	public static final DeferredItem<Item> ALPHA_YETI_TROPHY = register(TFItemIds.ALPHA_YETI_TROPHY, properties -> new StandingAndWallBlockItem(TFBlocks.ALPHA_YETI_TROPHY.get(), TFBlocks.ALPHA_YETI_WALL_TROPHY.get(), Direction.DOWN, properties), () -> new Item.Properties().useBlockDescriptionPrefix().rarity(tfRarityEnumExtension.TWILIGHT).equippable(EquipmentSlot.HEAD));
	public static final DeferredItem<Item> SNOW_QUEEN_TROPHY = register(TFItemIds.SNOW_QUEEN_TROPHY, properties -> new StandingAndWallBlockItem(TFBlocks.SNOW_QUEEN_TROPHY.get(), TFBlocks.SNOW_QUEEN_WALL_TROPHY.get(), Direction.DOWN, properties), () -> new Item.Properties().useBlockDescriptionPrefix().rarity(tfRarityEnumExtension.TWILIGHT).equippable(EquipmentSlot.HEAD));
	public static final DeferredItem<Item> QUEST_RAM_TROPHY = register(TFItemIds.QUEST_RAM_TROPHY, properties -> new StandingAndWallBlockItem(TFBlocks.QUEST_RAM_TROPHY.get(), TFBlocks.QUEST_RAM_WALL_TROPHY.get(), Direction.DOWN, properties), () -> new Item.Properties().useBlockDescriptionPrefix().rarity(tfRarityEnumExtension.TWILIGHT).equippable(EquipmentSlot.HEAD));

	public static final DeferredItem<HollowLogItem> HOLLOW_TWILIGHT_OAK_LOG = register(TFItemIds.HOLLOW_TWILIGHT_OAK_LOG, properties -> new HollowLogItem(TFBlocks.HOLLOW_TWILIGHT_OAK_LOG_HORIZONTAL, TFBlocks.HOLLOW_TWILIGHT_OAK_LOG_VERTICAL, TFBlocks.HOLLOW_TWILIGHT_OAK_LOG_CLIMBABLE, properties), () -> new Item.Properties().useBlockDescriptionPrefix());
	public static final DeferredItem<HollowLogItem> HOLLOW_CANOPY_LOG = register(TFItemIds.HOLLOW_CANOPY_LOG, properties -> new HollowLogItem(TFBlocks.HOLLOW_CANOPY_LOG_HORIZONTAL, TFBlocks.HOLLOW_CANOPY_LOG_VERTICAL, TFBlocks.HOLLOW_CANOPY_LOG_CLIMBABLE, properties), () -> new Item.Properties().useBlockDescriptionPrefix());
	public static final DeferredItem<HollowLogItem> HOLLOW_MANGROVE_LOG = register(TFItemIds.HOLLOW_MANGROVE_LOG, properties -> new HollowLogItem(TFBlocks.HOLLOW_MANGROVE_LOG_HORIZONTAL, TFBlocks.HOLLOW_MANGROVE_LOG_VERTICAL, TFBlocks.HOLLOW_MANGROVE_LOG_CLIMBABLE, properties), () -> new Item.Properties().useBlockDescriptionPrefix());
	public static final DeferredItem<HollowLogItem> HOLLOW_DARK_LOG = register(TFItemIds.HOLLOW_DARK_LOG, properties -> new HollowLogItem(TFBlocks.HOLLOW_DARK_LOG_HORIZONTAL, TFBlocks.HOLLOW_DARK_LOG_VERTICAL, TFBlocks.HOLLOW_DARK_LOG_CLIMBABLE, properties), () -> new Item.Properties().useBlockDescriptionPrefix());
	public static final DeferredItem<HollowLogItem> HOLLOW_TIME_LOG = register(TFItemIds.HOLLOW_TIME_LOG, properties -> new HollowLogItem(TFBlocks.HOLLOW_TIME_LOG_HORIZONTAL, TFBlocks.HOLLOW_TIME_LOG_VERTICAL, TFBlocks.HOLLOW_TIME_LOG_CLIMBABLE, properties), () -> new Item.Properties().useBlockDescriptionPrefix());
	public static final DeferredItem<HollowLogItem> HOLLOW_TRANSFORMATION_LOG = register(TFItemIds.HOLLOW_TRANSFORMATION_LOG, properties -> new HollowLogItem(TFBlocks.HOLLOW_TRANSFORMATION_LOG_HORIZONTAL, TFBlocks.HOLLOW_TRANSFORMATION_LOG_VERTICAL, TFBlocks.HOLLOW_TRANSFORMATION_LOG_CLIMBABLE, properties), () -> new Item.Properties().useBlockDescriptionPrefix());
	public static final DeferredItem<HollowLogItem> HOLLOW_MINING_LOG = register(TFItemIds.HOLLOW_MINING_LOG, properties -> new HollowLogItem(TFBlocks.HOLLOW_MINING_LOG_HORIZONTAL, TFBlocks.HOLLOW_MINING_LOG_VERTICAL, TFBlocks.HOLLOW_MINING_LOG_CLIMBABLE, properties), () -> new Item.Properties().useBlockDescriptionPrefix());
	public static final DeferredItem<HollowLogItem> HOLLOW_SORTING_LOG = register(TFItemIds.HOLLOW_SORTING_LOG, properties -> new HollowLogItem(TFBlocks.HOLLOW_SORTING_LOG_HORIZONTAL, TFBlocks.HOLLOW_SORTING_LOG_VERTICAL, TFBlocks.HOLLOW_SORTING_LOG_CLIMBABLE, properties), () -> new Item.Properties().useBlockDescriptionPrefix());

	public static final DeferredItem<HollowLogItem> HOLLOW_OAK_LOG = register(TFItemIds.HOLLOW_OAK_LOG, properties -> new HollowLogItem(TFBlocks.HOLLOW_OAK_LOG_HORIZONTAL, TFBlocks.HOLLOW_OAK_LOG_VERTICAL, TFBlocks.HOLLOW_OAK_LOG_CLIMBABLE, properties), () -> new Item.Properties().useBlockDescriptionPrefix());
	public static final DeferredItem<HollowLogItem> HOLLOW_SPRUCE_LOG = register(TFItemIds.HOLLOW_SPRUCE_LOG, properties -> new HollowLogItem(TFBlocks.HOLLOW_SPRUCE_LOG_HORIZONTAL, TFBlocks.HOLLOW_SPRUCE_LOG_VERTICAL, TFBlocks.HOLLOW_SPRUCE_LOG_CLIMBABLE, properties), () -> new Item.Properties().useBlockDescriptionPrefix());
	public static final DeferredItem<HollowLogItem> HOLLOW_BIRCH_LOG = register(TFItemIds.HOLLOW_BIRCH_LOG, properties -> new HollowLogItem(TFBlocks.HOLLOW_BIRCH_LOG_HORIZONTAL, TFBlocks.HOLLOW_BIRCH_LOG_VERTICAL, TFBlocks.HOLLOW_BIRCH_LOG_CLIMBABLE, properties), () -> new Item.Properties().useBlockDescriptionPrefix());
	public static final DeferredItem<HollowLogItem> HOLLOW_JUNGLE_LOG = register(TFItemIds.HOLLOW_JUNGLE_LOG, properties -> new HollowLogItem(TFBlocks.HOLLOW_JUNGLE_LOG_HORIZONTAL, TFBlocks.HOLLOW_JUNGLE_LOG_VERTICAL, TFBlocks.HOLLOW_JUNGLE_LOG_CLIMBABLE, properties), () -> new Item.Properties().useBlockDescriptionPrefix());
	public static final DeferredItem<HollowLogItem> HOLLOW_ACACIA_LOG = register(TFItemIds.HOLLOW_ACACIA_LOG, properties -> new HollowLogItem(TFBlocks.HOLLOW_ACACIA_LOG_HORIZONTAL, TFBlocks.HOLLOW_ACACIA_LOG_VERTICAL, TFBlocks.HOLLOW_ACACIA_LOG_CLIMBABLE, properties), () -> new Item.Properties().useBlockDescriptionPrefix());
	public static final DeferredItem<HollowLogItem> HOLLOW_DARK_OAK_LOG = register(TFItemIds.HOLLOW_DARK_OAK_LOG, properties -> new HollowLogItem(TFBlocks.HOLLOW_DARK_OAK_LOG_HORIZONTAL, TFBlocks.HOLLOW_DARK_OAK_LOG_VERTICAL, TFBlocks.HOLLOW_DARK_OAK_LOG_CLIMBABLE, properties), () -> new Item.Properties().useBlockDescriptionPrefix());
	public static final DeferredItem<HollowLogItem> HOLLOW_CRIMSON_STEM = register(TFItemIds.HOLLOW_CRIMSON_STEM, properties -> new HollowLogItem(TFBlocks.HOLLOW_CRIMSON_STEM_HORIZONTAL, TFBlocks.HOLLOW_CRIMSON_STEM_VERTICAL, TFBlocks.HOLLOW_CRIMSON_STEM_CLIMBABLE, properties), () -> new Item.Properties().useBlockDescriptionPrefix());
	public static final DeferredItem<HollowLogItem> HOLLOW_WARPED_STEM = register(TFItemIds.HOLLOW_WARPED_STEM, properties -> new HollowLogItem(TFBlocks.HOLLOW_WARPED_STEM_HORIZONTAL, TFBlocks.HOLLOW_WARPED_STEM_VERTICAL, TFBlocks.HOLLOW_WARPED_STEM_CLIMBABLE, properties), () -> new Item.Properties().useBlockDescriptionPrefix());
	public static final DeferredItem<HollowLogItem> HOLLOW_VANGROVE_LOG = register(TFItemIds.HOLLOW_VANGROVE_LOG, properties -> new HollowLogItem(TFBlocks.HOLLOW_VANGROVE_LOG_HORIZONTAL, TFBlocks.HOLLOW_VANGROVE_LOG_VERTICAL, TFBlocks.HOLLOW_VANGROVE_LOG_CLIMBABLE, properties), () -> new Item.Properties().useBlockDescriptionPrefix());
	public static final DeferredItem<HollowLogItem> HOLLOW_CHERRY_LOG = register(TFItemIds.HOLLOW_CHERRY_LOG, properties -> new HollowLogItem(TFBlocks.HOLLOW_CHERRY_LOG_HORIZONTAL, TFBlocks.HOLLOW_CHERRY_LOG_VERTICAL, TFBlocks.HOLLOW_CHERRY_LOG_CLIMBABLE, properties), () -> new Item.Properties().useBlockDescriptionPrefix());
	public static final DeferredItem<HollowLogItem> HOLLOW_PALE_OAK_LOG = register(TFItemIds.HOLLOW_PALE_OAK_LOG, properties -> new HollowLogItem(TFBlocks.HOLLOW_PALE_OAK_LOG_HORIZONTAL, TFBlocks.HOLLOW_PALE_OAK_LOG_VERTICAL, TFBlocks.HOLLOW_PALE_OAK_LOG_CLIMBABLE, properties), () -> new Item.Properties().useBlockDescriptionPrefix());

	public static final DeferredItem<Item> TWILIGHT_OAK_SIGN = register(TFItemIds.TWILIGHT_OAK_SIGN, properties -> new SignItem(TFBlocks.TWILIGHT_OAK_SIGN.get(), TFBlocks.TWILIGHT_WALL_SIGN.get(), properties), () -> new Item.Properties().useBlockDescriptionPrefix().stacksTo(16));
	public static final DeferredItem<Item> TWILIGHT_OAK_HANGING_SIGN = register(TFItemIds.TWILIGHT_OAK_HANGING_SIGN, properties -> new HangingSignItem(TFBlocks.TWILIGHT_OAK_HANGING_SIGN.get(), TFBlocks.TWILIGHT_OAK_WALL_HANGING_SIGN.get(), properties), () -> new Item.Properties().useBlockDescriptionPrefix().stacksTo(16));
	public static final DeferredItem<Item> CANOPY_SIGN = register(TFItemIds.CANOPY_SIGN, properties -> new SignItem(TFBlocks.CANOPY_SIGN.get(), TFBlocks.CANOPY_WALL_SIGN.get(), properties), () -> new Item.Properties().useBlockDescriptionPrefix().stacksTo(16));
	public static final DeferredItem<Item> CANOPY_HANGING_SIGN = register(TFItemIds.CANOPY_HANGING_SIGN, properties -> new HangingSignItem(TFBlocks.CANOPY_HANGING_SIGN.get(), TFBlocks.CANOPY_WALL_HANGING_SIGN.get(), properties), () -> new Item.Properties().useBlockDescriptionPrefix().stacksTo(16));
	public static final DeferredItem<Item> MANGROVE_SIGN = register(TFItemIds.MANGROVE_SIGN, properties -> new SignItem(TFBlocks.MANGROVE_SIGN.get(), TFBlocks.MANGROVE_WALL_SIGN.get(), properties), () -> new Item.Properties().useBlockDescriptionPrefix().stacksTo(16));
	public static final DeferredItem<Item> MANGROVE_HANGING_SIGN = register(TFItemIds.MANGROVE_HANGING_SIGN, properties -> new HangingSignItem(TFBlocks.MANGROVE_HANGING_SIGN.get(), TFBlocks.MANGROVE_WALL_HANGING_SIGN.get(), properties), () -> new Item.Properties().useBlockDescriptionPrefix().stacksTo(16));
	public static final DeferredItem<Item> DARK_SIGN = register(TFItemIds.DARK_SIGN, properties -> new SignItem(TFBlocks.DARK_SIGN.get(), TFBlocks.DARK_WALL_SIGN.get(), properties), () -> new Item.Properties().useBlockDescriptionPrefix().stacksTo(16));
	public static final DeferredItem<Item> DARK_HANGING_SIGN = register(TFItemIds.DARK_HANGING_SIGN, properties -> new HangingSignItem(TFBlocks.DARK_HANGING_SIGN.get(), TFBlocks.DARK_WALL_HANGING_SIGN.get(), properties), () -> new Item.Properties().useBlockDescriptionPrefix().stacksTo(16));
	public static final DeferredItem<Item> TIME_SIGN = register(TFItemIds.TIME_SIGN, properties -> new SignItem(TFBlocks.TIME_SIGN.get(), TFBlocks.TIME_WALL_SIGN.get(), properties), () -> new Item.Properties().useBlockDescriptionPrefix().stacksTo(16));
	public static final DeferredItem<Item> TIME_HANGING_SIGN = register(TFItemIds.TIME_HANGING_SIGN, properties -> new HangingSignItem(TFBlocks.TIME_HANGING_SIGN.get(), TFBlocks.TIME_WALL_HANGING_SIGN.get(), properties), () -> new Item.Properties().useBlockDescriptionPrefix().stacksTo(16));
	public static final DeferredItem<Item> TRANSFORMATION_SIGN = register(TFItemIds.TRANSFORMATION_SIGN, properties -> new SignItem(TFBlocks.TRANSFORMATION_SIGN.get(), TFBlocks.TRANSFORMATION_WALL_SIGN.get(), properties), () -> new Item.Properties().useBlockDescriptionPrefix().stacksTo(16));
	public static final DeferredItem<Item> TRANSFORMATION_HANGING_SIGN = register(TFItemIds.TRANSFORMATION_HANGING_SIGN, properties -> new HangingSignItem(TFBlocks.TRANSFORMATION_HANGING_SIGN.get(), TFBlocks.TRANSFORMATION_WALL_HANGING_SIGN.get(), properties), () -> new Item.Properties().useBlockDescriptionPrefix().stacksTo(16));
	public static final DeferredItem<Item> MINING_SIGN = register(TFItemIds.MINING_SIGN, properties -> new SignItem(TFBlocks.MINING_SIGN.get(), TFBlocks.MINING_WALL_SIGN.get(), properties), () -> new Item.Properties().useBlockDescriptionPrefix().stacksTo(16));
	public static final DeferredItem<Item> MINING_HANGING_SIGN = register(TFItemIds.MINING_HANGING_SIGN, properties -> new HangingSignItem(TFBlocks.MINING_HANGING_SIGN.get(), TFBlocks.MINING_WALL_HANGING_SIGN.get(), properties), () -> new Item.Properties().useBlockDescriptionPrefix().stacksTo(16));
	public static final DeferredItem<Item> SORTING_SIGN = register(TFItemIds.SORTING_SIGN, properties -> new SignItem(TFBlocks.SORTING_SIGN.get(), TFBlocks.SORTING_WALL_SIGN.get(), properties), () -> new Item.Properties().useBlockDescriptionPrefix().stacksTo(16));
	public static final DeferredItem<Item> SORTING_HANGING_SIGN = register(TFItemIds.SORTING_HANGING_SIGN, properties -> new HangingSignItem(TFBlocks.SORTING_HANGING_SIGN.get(), TFBlocks.SORTING_WALL_HANGING_SIGN.get(), properties), () -> new Item.Properties().useBlockDescriptionPrefix().stacksTo(16));

	public static final DeferredItem<Item> TWILIGHT_OAK_BOAT = register(TFItemIds.TWILIGHT_OAK_BOAT, properties -> new BoatItem(TFEntities.TWILIGHT_OAK_BOAT.get(), properties), () -> new Item.Properties().stacksTo(1));
	public static final DeferredItem<Item> TWILIGHT_OAK_CHEST_BOAT = register(TFItemIds.TWILIGHT_OAK_CHEST_BOAT, properties -> new BoatItem(TFEntities.TWILIGHT_OAK_CHEST_BOAT.get(), properties), () -> new Item.Properties().stacksTo(1));
	public static final DeferredItem<Item> CANOPY_BOAT = register(TFItemIds.CANOPY_BOAT, properties -> new BoatItem(TFEntities.CANOPY_BOAT.get(), properties), () -> new Item.Properties().stacksTo(1));
	public static final DeferredItem<Item> CANOPY_CHEST_BOAT = register(TFItemIds.CANOPY_CHEST_BOAT, properties -> new BoatItem(TFEntities.CANOPY_CHEST_BOAT.get(), properties), () -> new Item.Properties().stacksTo(1));
	public static final DeferredItem<Item> MANGROVE_BOAT = register(TFItemIds.MANGROVE_BOAT, properties -> new BoatItem(TFEntities.MANGROVE_BOAT.get(), properties), () -> new Item.Properties().stacksTo(1));
	public static final DeferredItem<Item> MANGROVE_CHEST_BOAT = register(TFItemIds.MANGROVE_CHEST_BOAT, properties -> new BoatItem(TFEntities.MANGROVE_CHEST_BOAT.get(), properties), () -> new Item.Properties().stacksTo(1));
	public static final DeferredItem<Item> DARK_BOAT = register(TFItemIds.DARK_BOAT, properties -> new BoatItem(TFEntities.DARK_BOAT.get(), properties), () -> new Item.Properties().stacksTo(1));
	public static final DeferredItem<Item> DARK_CHEST_BOAT = register(TFItemIds.DARK_CHEST_BOAT, properties -> new BoatItem(TFEntities.DARK_CHEST_BOAT.get(), properties), () -> new Item.Properties().stacksTo(1));
	public static final DeferredItem<Item> TIME_BOAT = register(TFItemIds.TIME_BOAT, properties -> new BoatItem(TFEntities.TIME_BOAT.get(), properties), () -> new Item.Properties().stacksTo(1));
	public static final DeferredItem<Item> TIME_CHEST_BOAT = register(TFItemIds.TIME_CHEST_BOAT, properties -> new BoatItem(TFEntities.TIME_CHEST_BOAT.get(), properties), () -> new Item.Properties().stacksTo(1));
	public static final DeferredItem<Item> TRANSFORMATION_BOAT = register(TFItemIds.TRANSFORMATION_BOAT, properties -> new BoatItem(TFEntities.TRANSFORMATION_BOAT.get(), properties), () -> new Item.Properties().stacksTo(1));
	public static final DeferredItem<Item> TRANSFORMATION_CHEST_BOAT = register(TFItemIds.TRANSFORMATION_CHEST_BOAT, properties -> new BoatItem(TFEntities.TRANSFORMATION_CHEST_BOAT.get(), properties), () -> new Item.Properties().stacksTo(1));
	public static final DeferredItem<Item> MINING_BOAT = register(TFItemIds.MINING_BOAT, properties -> new BoatItem(TFEntities.MINING_BOAT.get(), properties), () -> new Item.Properties().stacksTo(1));
	public static final DeferredItem<Item> MINING_CHEST_BOAT = register(TFItemIds.MINING_CHEST_BOAT, properties -> new BoatItem(TFEntities.MINING_CHEST_BOAT.get(), properties), () -> new Item.Properties().stacksTo(1));
	public static final DeferredItem<Item> SORTING_BOAT = register(TFItemIds.SORTING_BOAT, properties -> new BoatItem(TFEntities.SORTING_BOAT.get(), properties), () -> new Item.Properties().stacksTo(1));
	public static final DeferredItem<Item> SORTING_CHEST_BOAT = register(TFItemIds.SORTING_CHEST_BOAT, properties -> new BoatItem(TFEntities.SORTING_CHEST_BOAT.get(), properties), () -> new Item.Properties().stacksTo(1));

	public static final DeferredItem<Item> MUSIC_DISC_RADIANCE = register(TFItemIds.MUSIC_DISC_RADIANCE, Item::new, () -> new Item.Properties().stacksTo(1).rarity(Rarity.RARE).jukeboxPlayable(TFJukeboxSongs.RADIANCE));
	public static final DeferredItem<Item> MUSIC_DISC_STEPS = register(TFItemIds.MUSIC_DISC_STEPS, Item::new, () -> new Item.Properties().stacksTo(1).rarity(Rarity.RARE).jukeboxPlayable(TFJukeboxSongs.STEPS));
	public static final DeferredItem<Item> MUSIC_DISC_SUPERSTITIOUS = register(TFItemIds.MUSIC_DISC_SUPERSTITIOUS, Item::new, () -> new Item.Properties().stacksTo(1).rarity(Rarity.RARE).jukeboxPlayable(TFJukeboxSongs.SUPERSTITIOUS));
	public static final DeferredItem<Item> MUSIC_DISC_HOME = register(TFItemIds.MUSIC_DISC_HOME, Item::new, () -> new Item.Properties().stacksTo(1).rarity(Rarity.RARE).jukeboxPlayable(TFJukeboxSongs.HOME));
	public static final DeferredItem<Item> MUSIC_DISC_WAYFARER = register(TFItemIds.MUSIC_DISC_WAYFARER, Item::new, () -> new Item.Properties().stacksTo(1).rarity(Rarity.RARE).jukeboxPlayable(TFJukeboxSongs.WAYFARER));
	public static final DeferredItem<Item> MUSIC_DISC_FINDINGS = register(TFItemIds.MUSIC_DISC_FINDINGS, Item::new, () -> new Item.Properties().stacksTo(1).rarity(Rarity.RARE).jukeboxPlayable(TFJukeboxSongs.FINDINGS));
	public static final DeferredItem<Item> MUSIC_DISC_MAKER = register(TFItemIds.MUSIC_DISC_MAKER, Item::new, () -> new Item.Properties().stacksTo(1).rarity(Rarity.RARE).jukeboxPlayable(TFJukeboxSongs.MAKER));
	public static final DeferredItem<Item> MUSIC_DISC_THREAD = register(TFItemIds.MUSIC_DISC_THREAD, Item::new, () -> new Item.Properties().stacksTo(1).rarity(Rarity.RARE).jukeboxPlayable(TFJukeboxSongs.THREAD));
	public static final DeferredItem<Item> MUSIC_DISC_MOTION = register(TFItemIds.MUSIC_DISC_MOTION, Item::new, () -> new Item.Properties().stacksTo(1).rarity(Rarity.RARE).jukeboxPlayable(TFJukeboxSongs.MOTION));

	public static final DeferredItem<Item> NAGA_BANNER_PATTERN = register(TFItemIds.NAGA_BANNER_PATTERN, Item::new, () -> new Item.Properties().delayedComponent(DataComponents.PROVIDES_BANNER_PATTERNS, context -> context.getOrThrow(TFBannerPatternTags.NAGA_BANNER_PATTERN)).stacksTo(1).rarity(tfRarityEnumExtension.TWILIGHT));
	public static final DeferredItem<Item> LICH_BANNER_PATTERN = register(TFItemIds.LICH_BANNER_PATTERN, Item::new, () -> new Item.Properties().delayedComponent(DataComponents.PROVIDES_BANNER_PATTERNS, context -> context.getOrThrow(TFBannerPatternTags.LICH_BANNER_PATTERN)).stacksTo(1).rarity(tfRarityEnumExtension.TWILIGHT));
	public static final DeferredItem<Item> MINOSHROOM_BANNER_PATTERN = register(TFItemIds.MINOSHROOM_BANNER_PATTERN, Item::new, () -> new Item.Properties().delayedComponent(DataComponents.PROVIDES_BANNER_PATTERNS, context -> context.getOrThrow(TFBannerPatternTags.MINOSHROOM_BANNER_PATTERN)).stacksTo(1).rarity(tfRarityEnumExtension.TWILIGHT));
	public static final DeferredItem<Item> HYDRA_BANNER_PATTERN = register(TFItemIds.HYDRA_BANNER_PATTERN, Item::new, () -> new Item.Properties().delayedComponent(DataComponents.PROVIDES_BANNER_PATTERNS, context -> context.getOrThrow(TFBannerPatternTags.HYDRA_BANNER_PATTERN)).stacksTo(1).rarity(tfRarityEnumExtension.TWILIGHT));
	public static final DeferredItem<Item> KNIGHT_PHANTOM_BANNER_PATTERN = register(TFItemIds.KNIGHT_PHANTOM_BANNER_PATTERN, Item::new, () -> new Item.Properties().delayedComponent(DataComponents.PROVIDES_BANNER_PATTERNS, context -> context.getOrThrow(TFBannerPatternTags.KNIGHT_PHANTOM_BANNER_PATTERN)).stacksTo(1).rarity(tfRarityEnumExtension.TWILIGHT));
	public static final DeferredItem<Item> UR_GHAST_BANNER_PATTERN = register(TFItemIds.UR_GHAST_BANNER_PATTERN, Item::new, () -> new Item.Properties().delayedComponent(DataComponents.PROVIDES_BANNER_PATTERNS, context -> context.getOrThrow(TFBannerPatternTags.UR_GHAST_BANNER_PATTERN)).stacksTo(1).rarity(tfRarityEnumExtension.TWILIGHT));
	public static final DeferredItem<Item> ALPHA_YETI_BANNER_PATTERN = register(TFItemIds.ALPHA_YETI_BANNER_PATTERN, Item::new, () -> new Item.Properties().delayedComponent(DataComponents.PROVIDES_BANNER_PATTERNS, context -> context.getOrThrow(TFBannerPatternTags.ALPHA_YETI_BANNER_PATTERN)).stacksTo(1).rarity(tfRarityEnumExtension.TWILIGHT));
	public static final DeferredItem<Item> SNOW_QUEEN_BANNER_PATTERN = register(TFItemIds.SNOW_QUEEN_BANNER_PATTERN, Item::new, () -> new Item.Properties().delayedComponent(DataComponents.PROVIDES_BANNER_PATTERNS, context -> context.getOrThrow(TFBannerPatternTags.SNOW_QUEEN_BANNER_PATTERN)).stacksTo(1).rarity(tfRarityEnumExtension.TWILIGHT));
	public static final DeferredItem<Item> QUEST_RAM_BANNER_PATTERN = register(TFItemIds.QUEST_RAM_BANNER_PATTERN, Item::new, () -> new Item.Properties().delayedComponent(DataComponents.PROVIDES_BANNER_PATTERNS, context -> context.getOrThrow(TFBannerPatternTags.QUESTING_RAM_BANNER_PATTERN)).stacksTo(1).rarity(tfRarityEnumExtension.TWILIGHT));

	public static final DeferredItem<Item> RASPBERRY = register(TFItemIds.RASPBERRY, Item::new, () -> new Item.Properties().food(TFFoods.BERRY));
	public static final DeferredItem<Item> BLUEBERRY = register(TFItemIds.BLUEBERRY, Item::new, () -> new Item.Properties().food(TFFoods.BERRY));
	public static final DeferredItem<Item> BLACKBERRY = register(TFItemIds.BLACKBERRY, Item::new, () -> new Item.Properties().food(TFFoods.BERRY));
	public static final DeferredItem<Item> MALOBERRY = register(TFItemIds.MALOBERRY, Item::new, () -> new Item.Properties().food(TFFoods.BERRY));
	public static final DeferredItem<Item> BLIGHTBERRY = register(TFItemIds.BLIGHTBERRY, Item::new, () -> new Item.Properties().food(TFFoods.BERRY, TFConsumables.BLIGHTBERRY));
	public static final DeferredItem<Item> DUSKBERRY = register(TFItemIds.DUSKBERRY, Item::new, () -> new Item.Properties().food(TFFoods.BERRY, TFConsumables.DUSKBERRY));
	public static final DeferredItem<Item> SKYBERRY = register(TFItemIds.SKYBERRY, Item::new, () -> new Item.Properties().food(TFFoods.BERRY, TFConsumables.SKYBERRY));
	public static final DeferredItem<Item> STINGBERRY = register(TFItemIds.STINGBERRY, Item::new, () -> new Item.Properties().food(TFFoods.BERRY, TFConsumables.STINGBERRY));
	public static final DeferredItem<Item> BERRY_MEDLEY = register(TFItemIds.BERRY_MEDLEY, Item::new, () -> new Item.Properties().food(TFFoods.BERRY_MEDLEY).usingConvertsTo(Items.BOWL).stacksTo(1));
	public static final DeferredItem<Item> MOSS_SOUP = register(TFItemIds.MOSS_SOUP, Item::new, () -> new Item.Properties().food(TFFoods.MOSS_SOUP).usingConvertsTo(Items.BOWL).stacksTo(1));
	public static final DeferredItem<Item> SHIKA_SENBEI = register(TFItemIds.SHIKA_SENBEI, Item::new, () -> new Item.Properties().food(TFFoods.SHIKA_SENBEI));

	public static final DeferredItem<Item> MONSTER_JERKY = register(TFItemIds.MONSTER_JERKY, Item::new, () -> new Item.Properties().food(TFFoods.MONSTER_JERKY));
	public static final DeferredItem<Item> BEEF_JERKY = register(TFItemIds.BEEF_JERKY, Item::new, () -> new Item.Properties().food(TFFoods.BEEF_JERKY));
	public static final DeferredItem<Item> CHICKEN_JERKY = register(TFItemIds.CHICKEN_JERKY, Item::new, () -> new Item.Properties().food(TFFoods.CHICKEN_JERKY));
	public static final DeferredItem<Item> PORK_JERKY = register(TFItemIds.PORK_JERKY, Item::new, () -> new Item.Properties().food(TFFoods.PORK_JERKY));
	public static final DeferredItem<Item> MUTTON_JERKY = register(TFItemIds.MUTTON_JERKY, Item::new, () -> new Item.Properties().food(TFFoods.MUTTON_JERKY));
	public static final DeferredItem<Item> RABBIT_JERKY = register(TFItemIds.RABBIT_JERKY, Item::new, () -> new Item.Properties().food(TFFoods.RABBIT_JERKY));
	public static final DeferredItem<Item> COD_JERKY = register(TFItemIds.COD_JERKY, Item::new, () -> new Item.Properties().food(TFFoods.COD_JERKY));
	public static final DeferredItem<Item> SALMON_JERKY = register(TFItemIds.SALMON_JERKY, Item::new, () -> new Item.Properties().food(TFFoods.SALMON_JERKY));
	public static final DeferredItem<Item> TROPICAL_FISH_JERKY = register(TFItemIds.TROPICAL_FISH_JERKY, Item::new, () -> new Item.Properties().food(TFFoods.TROPICAL_FISH_JERKY));
	public static final DeferredItem<Item> FUGU_JERKY = register(TFItemIds.FUGU_JERKY, Item::new, () -> new Item.Properties().food(TFFoods.FUGU_JERKY));
	public static final DeferredItem<Item> VENISON_JERKY = register(TFItemIds.VENISON_JERKY, Item::new, () -> new Item.Properties().food(TFFoods.VENISON_JERKY));
	public static final DeferredItem<Item> MEEF_JERKY = register(TFItemIds.MEEF_JERKY, Item::new, () -> new Item.Properties().food(TFFoods.MEEF_JERKY));

	public static final DeferredItem<Item> GELATINOUS_SLIME_DROP = register(TFItemIds.GELATINOUS_SLIME_DROP, Item::new, () -> new Item.Properties().food(TFFoods.SLIME_DROP, TFConsumables.SLIME_DROP));
	public static final DeferredItem<Item> GELATINOUS_MAZE_SLIME_DROP = register(TFItemIds.GELATINOUS_MAZE_SLIME_DROP, Item::new, () -> new Item.Properties().food(TFFoods.MAZE_SLIME_DROP, TFConsumables.MAZE_SLIME_DROP));

	public static final DeferredItem<Item> TREATED_LEATHER = register(TFItemIds.TREATED_LEATHER, Item::new, Item.Properties::new);
	public static final DeferredItem<Item> TANNED_LEATHER = register(TFItemIds.TANNED_LEATHER, Item::new, Item.Properties::new);

	public static final DeferredItem<Item> ALPHA_YETI_SPAWN_EGG = registerSpawnEgg(TFItemIds.ALPHA_YETI_SPAWN_EGG, TFEntities.ALPHA_YETI);
	public static final DeferredItem<Item> ARMORED_GIANT_SPAWN_EGG = registerSpawnEgg(TFItemIds.ARMORED_GIANT_SPAWN_EGG, TFEntities.ARMORED_GIANT);
	public static final DeferredItem<Item> BIGHORN_SHEEP_SPAWN_EGG = registerSpawnEgg(TFItemIds.BIGHORN_SHEEP_SPAWN_EGG, TFEntities.BIGHORN_SHEEP);
	public static final DeferredItem<Item> BLOCKCHAIN_GOBLIN_SPAWN_EGG = registerSpawnEgg(TFItemIds.BLOCKCHAIN_GOBLIN_SPAWN_EGG, TFEntities.BLOCKCHAIN_GOBLIN);
	public static final DeferredItem<Item> BOAR_SPAWN_EGG = registerSpawnEgg(TFItemIds.BOAR_SPAWN_EGG, TFEntities.BOAR);
	public static final DeferredItem<Item> CARMINITE_BROODLING_SPAWN_EGG = registerSpawnEgg(TFItemIds.CARMINITE_BROODLING_SPAWN_EGG, TFEntities.CARMINITE_BROODLING);
	public static final DeferredItem<Item> CARMINITE_GHASTGUARD_SPAWN_EGG = registerSpawnEgg(TFItemIds.CARMINITE_GHASTGUARD_SPAWN_EGG, TFEntities.CARMINITE_GHASTGUARD);
	public static final DeferredItem<Item> CARMINITE_GHASTLING_SPAWN_EGG = registerSpawnEgg(TFItemIds.CARMINITE_GHASTLING_SPAWN_EGG, TFEntities.CARMINITE_GHASTLING);
	public static final DeferredItem<Item> CARMINITE_GOLEM_SPAWN_EGG = registerSpawnEgg(TFItemIds.CARMINITE_GOLEM_SPAWN_EGG, TFEntities.CARMINITE_GOLEM);
	public static final DeferredItem<Item> DEATH_TOME_SPAWN_EGG = registerSpawnEgg(TFItemIds.DEATH_TOME_SPAWN_EGG, TFEntities.DEATH_TOME);
	public static final DeferredItem<Item> DEER_SPAWN_EGG = registerSpawnEgg(TFItemIds.DEER_SPAWN_EGG, TFEntities.DEER);
	public static final DeferredItem<Item> DWARF_RABBIT_SPAWN_EGG = registerSpawnEgg(TFItemIds.DWARF_RABBIT_SPAWN_EGG, TFEntities.DWARF_RABBIT);
	public static final DeferredItem<Item> FIRE_BEETLE_SPAWN_EGG = registerSpawnEgg(TFItemIds.FIRE_BEETLE_SPAWN_EGG, TFEntities.FIRE_BEETLE);
	public static final DeferredItem<Item> GIANT_MINER_SPAWN_EGG = registerSpawnEgg(TFItemIds.GIANT_MINER_SPAWN_EGG, TFEntities.GIANT_MINER);
	public static final DeferredItem<Item> HEDGE_SPIDER_SPAWN_EGG = registerSpawnEgg(TFItemIds.HEDGE_SPIDER_SPAWN_EGG, TFEntities.HEDGE_SPIDER);
	public static final DeferredItem<Item> HELMET_CRAB_SPAWN_EGG = registerSpawnEgg(TFItemIds.HELMET_CRAB_SPAWN_EGG, TFEntities.HELMET_CRAB);
	public static final DeferredItem<Item> HOSTILE_WOLF_SPAWN_EGG = registerSpawnEgg(TFItemIds.HOSTILE_WOLF_SPAWN_EGG, TFEntities.HOSTILE_WOLF);
	public static final DeferredItem<Item> HYDRA_SPAWN_EGG = registerSpawnEgg(TFItemIds.HYDRA_SPAWN_EGG, TFEntities.HYDRA);
	public static final DeferredItem<Item> ICE_CRYSTAL_SPAWN_EGG = registerSpawnEgg(TFItemIds.ICE_CRYSTAL_SPAWN_EGG, TFEntities.ICE_CRYSTAL);
	public static final DeferredItem<Item> KING_SPIDER_SPAWN_EGG = registerSpawnEgg(TFItemIds.KING_SPIDER_SPAWN_EGG, TFEntities.KING_SPIDER);
	public static final DeferredItem<Item> KNIGHT_PHANTOM_SPAWN_EGG = registerSpawnEgg(TFItemIds.KNIGHT_PHANTOM_SPAWN_EGG, TFEntities.KNIGHT_PHANTOM);
	public static final DeferredItem<Item> KOBOLD_SPAWN_EGG = registerSpawnEgg(TFItemIds.KOBOLD_SPAWN_EGG, TFEntities.KOBOLD);
	public static final DeferredItem<Item> LICH_SPAWN_EGG = registerSpawnEgg(TFItemIds.LICH_SPAWN_EGG, TFEntities.LICH);
	public static final DeferredItem<Item> LOWER_GOBLIN_KNIGHT_SPAWN_EGG = registerSpawnEgg(TFItemIds.LOWER_GOBLIN_KNIGHT_SPAWN_EGG, TFEntities.LOWER_GOBLIN_KNIGHT);
	public static final DeferredItem<Item> MAZE_SLIME_SPAWN_EGG = registerSpawnEgg(TFItemIds.MAZE_SLIME_SPAWN_EGG, TFEntities.MAZE_SLIME);
	public static final DeferredItem<Item> MINOSHROOM_SPAWN_EGG = registerSpawnEgg(TFItemIds.MINOSHROOM_SPAWN_EGG, TFEntities.MINOSHROOM);
	public static final DeferredItem<Item> MINOTAUR_SPAWN_EGG = registerSpawnEgg(TFItemIds.MINOTAUR_SPAWN_EGG, TFEntities.MINOTAUR);
	public static final DeferredItem<Item> MIST_WOLF_SPAWN_EGG = registerSpawnEgg(TFItemIds.MIST_WOLF_SPAWN_EGG, TFEntities.MIST_WOLF);
	public static final DeferredItem<Item> MOSQUITO_SWARM_SPAWN_EGG = registerSpawnEgg(TFItemIds.MOSQUITO_SWARM_SPAWN_EGG, TFEntities.MOSQUITO_SWARM);
	public static final DeferredItem<Item> NAGA_SPAWN_EGG = registerSpawnEgg(TFItemIds.NAGA_SPAWN_EGG, TFEntities.NAGA);
	public static final DeferredItem<Item> PENGUIN_SPAWN_EGG = registerSpawnEgg(TFItemIds.PENGUIN_SPAWN_EGG, TFEntities.PENGUIN);
	public static final DeferredItem<Item> PINCH_BEETLE_SPAWN_EGG = registerSpawnEgg(TFItemIds.PINCH_BEETLE_SPAWN_EGG, TFEntities.PINCH_BEETLE);
	public static final DeferredItem<Item> QUEST_RAM_SPAWN_EGG = registerSpawnEgg(TFItemIds.QUEST_RAM_SPAWN_EGG, TFEntities.QUEST_RAM);
	public static final DeferredItem<Item> RAVEN_SPAWN_EGG = registerSpawnEgg(TFItemIds.RAVEN_SPAWN_EGG, TFEntities.RAVEN);
	public static final DeferredItem<Item> REDCAP_SPAWN_EGG = registerSpawnEgg(TFItemIds.REDCAP_SPAWN_EGG, TFEntities.REDCAP);
	public static final DeferredItem<Item> REDCAP_SAPPER_SPAWN_EGG = registerSpawnEgg(TFItemIds.REDCAP_SAPPER_SPAWN_EGG, TFEntities.REDCAP_SAPPER);
	public static final DeferredItem<Item> SKELETON_DRUID_SPAWN_EGG = registerSpawnEgg(TFItemIds.SKELETON_DRUID_SPAWN_EGG, TFEntities.SKELETON_DRUID);
	public static final DeferredItem<Item> SLIME_BEETLE_SPAWN_EGG = registerSpawnEgg(TFItemIds.SLIME_BEETLE_SPAWN_EGG, TFEntities.SLIME_BEETLE);
	public static final DeferredItem<Item> SNOW_GUARDIAN_SPAWN_EGG = registerSpawnEgg(TFItemIds.SNOW_GUARDIAN_SPAWN_EGG, TFEntities.SNOW_GUARDIAN);
	public static final DeferredItem<Item> SNOW_QUEEN_SPAWN_EGG = registerSpawnEgg(TFItemIds.SNOW_QUEEN_SPAWN_EGG, TFEntities.SNOW_QUEEN);
	public static final DeferredItem<Item> SQUIRREL_SPAWN_EGG = registerSpawnEgg(TFItemIds.SQUIRREL_SPAWN_EGG, TFEntities.SQUIRREL);
	public static final DeferredItem<Item> STABLE_ICE_CORE_SPAWN_EGG = registerSpawnEgg(TFItemIds.STABLE_ICE_CORE_SPAWN_EGG, TFEntities.STABLE_ICE_CORE);
	public static final DeferredItem<Item> SWARM_SPIDER_SPAWN_EGG = registerSpawnEgg(TFItemIds.SWARM_SPIDER_SPAWN_EGG, TFEntities.SWARM_SPIDER);
	public static final DeferredItem<Item> TINY_BIRD_SPAWN_EGG = registerSpawnEgg(TFItemIds.TINY_BIRD_SPAWN_EGG, TFEntities.TINY_BIRD);
	public static final DeferredItem<Item> TOWERWOOD_BORER_SPAWN_EGG = registerSpawnEgg(TFItemIds.TOWERWOOD_BORER_SPAWN_EGG, TFEntities.TOWERWOOD_BORER);
	public static final DeferredItem<Item> TROLL_SPAWN_EGG = registerSpawnEgg(TFItemIds.TROLL_SPAWN_EGG, TFEntities.TROLL);
	public static final DeferredItem<Item> UNSTABLE_ICE_CORE_SPAWN_EGG = registerSpawnEgg(TFItemIds.UNSTABLE_ICE_CORE_SPAWN_EGG, TFEntities.UNSTABLE_ICE_CORE);
	public static final DeferredItem<Item> UR_GHAST_SPAWN_EGG = registerSpawnEgg(TFItemIds.UR_GHAST_SPAWN_EGG, TFEntities.UR_GHAST);
	public static final DeferredItem<Item> WINTER_WOLF_SPAWN_EGG = registerSpawnEgg(TFItemIds.WINTER_WOLF_SPAWN_EGG, TFEntities.WINTER_WOLF);
	public static final DeferredItem<Item> WRAITH_SPAWN_EGG = registerSpawnEgg(TFItemIds.WRAITH_SPAWN_EGG, TFEntities.WRAITH);
	public static final DeferredItem<Item> YETI_SPAWN_EGG = registerSpawnEgg(TFItemIds.YETI_SPAWN_EGG, TFEntities.YETI);

	public static <T extends Item> DeferredItem<T> register(ResourceKey<Item> key, Function<Item.Properties, T> item, Supplier<Item.Properties> properties) {
		return ITEMS.register(key.identifier().getPath(), () -> item.apply(properties.get().setId(key)));
	}

	private static <E extends LivingEntity> DeferredItem<Item> registerSpawnEgg(ResourceKey<Item> key, DeferredHolder<EntityType<?>, EntityType<E>> type) {
		return register(key, SpawnEggItem::new, () -> new Item.Properties().spawnEgg(type.get()));
	}
}